import { OpcodeDef } from '../types';

export const OPCODES_DATA: OpcodeDef[] = [
  // Data Transfer
  { hex: '78', mnemonic: 'MOV B, A', bytes: 1, tStates: '4', category: 'Data Transfer', flagsAffected: 'None', description: 'Copy content of Accumulator A into register B', example: 'MOV B, A' },
  { hex: '79', mnemonic: 'MOV C, A', bytes: 1, tStates: '4', category: 'Data Transfer', flagsAffected: 'None', description: 'Copy content of Accumulator A into register C', example: 'MOV C, A' },
  { hex: '7A', mnemonic: 'MOV D, A', bytes: 1, tStates: '4', category: 'Data Transfer', flagsAffected: 'None', description: 'Copy content of Accumulator A into register D', example: 'MOV D, A' },
  { hex: '7B', mnemonic: 'MOV E, A', bytes: 1, tStates: '4', category: 'Data Transfer', flagsAffected: 'None', description: 'Copy content of Accumulator A into register E', example: 'MOV E, A' },
  { hex: '7C', mnemonic: 'MOV H, A', bytes: 1, tStates: '4', category: 'Data Transfer', flagsAffected: 'None', description: 'Copy content of Accumulator A into register H', example: 'MOV H, A' },
  { hex: '7D', mnemonic: 'MOV L, A', bytes: 1, tStates: '4', category: 'Data Transfer', flagsAffected: 'None', description: 'Copy content of Accumulator A into register L', example: 'MOV L, A' },
  { hex: '77', mnemonic: 'MOV M, A', bytes: 1, tStates: '7', category: 'Data Transfer', flagsAffected: 'None', description: 'Store Accumulator A into memory location pointed by H-L pair', example: 'MOV M, A' },
  { hex: '7F', mnemonic: 'MOV A, A', bytes: 1, tStates: '4', category: 'Data Transfer', flagsAffected: 'None', description: 'Copy A to A', example: 'MOV A, A' },

  { hex: '47', mnemonic: 'MOV B, B', bytes: 1, tStates: '4', category: 'Data Transfer', flagsAffected: 'None', description: 'Copy B to B', example: 'MOV B, B' },
  { hex: '4F', mnemonic: 'MOV C, A', bytes: 1, tStates: '4', category: 'Data Transfer', flagsAffected: 'None', description: 'Copy A to C', example: 'MOV C, A' },
  { hex: '41', mnemonic: 'MOV B, C', bytes: 1, tStates: '4', category: 'Data Transfer', flagsAffected: 'None', description: 'Copy C to B', example: 'MOV B, C' },
  { hex: '42', mnemonic: 'MOV B, D', bytes: 1, tStates: '4', category: 'Data Transfer', flagsAffected: 'None', description: 'Copy D to B', example: 'MOV B, D' },
  { hex: '43', mnemonic: 'MOV B, E', bytes: 1, tStates: '4', category: 'Data Transfer', flagsAffected: 'None', description: 'Copy E to B', example: 'MOV B, E' },
  { hex: '44', mnemonic: 'MOV B, H', bytes: 1, tStates: '4', category: 'Data Transfer', flagsAffected: 'None', description: 'Copy H to B', example: 'MOV B, H' },
  { hex: '45', mnemonic: 'MOV B, L', bytes: 1, tStates: '4', category: 'Data Transfer', flagsAffected: 'None', description: 'Copy L to B', example: 'MOV B, L' },
  { hex: '46', mnemonic: 'MOV B, M', bytes: 1, tStates: '7', category: 'Data Transfer', flagsAffected: 'None', description: 'Copy memory byte at [HL] to B', example: 'MOV B, M' },

  { hex: '3E', mnemonic: 'MVI A, data', bytes: 2, tStates: '7', category: 'Data Transfer', flagsAffected: 'None', description: 'Move 8-bit immediate data into Accumulator A', example: 'MVI A, 05H' },
  { hex: '06', mnemonic: 'MVI B, data', bytes: 2, tStates: '7', category: 'Data Transfer', flagsAffected: 'None', description: 'Move 8-bit immediate data into register B', example: 'MVI B, 0AH' },
  { hex: '0E', mnemonic: 'MVI C, data', bytes: 2, tStates: '7', category: 'Data Transfer', flagsAffected: 'None', description: 'Move 8-bit immediate data into register C', example: 'MVI C, 20H' },
  { hex: '16', mnemonic: 'MVI D, data', bytes: 2, tStates: '7', category: 'Data Transfer', flagsAffected: 'None', description: 'Move 8-bit immediate data into register D', example: 'MVI D, 00H' },
  { hex: '1E', mnemonic: 'MVI E, data', bytes: 2, tStates: '7', category: 'Data Transfer', flagsAffected: 'None', description: 'Move 8-bit immediate data into register E', example: 'MVI E, FEH' },
  { hex: '26', mnemonic: 'MVI H, data', bytes: 2, tStates: '7', category: 'Data Transfer', flagsAffected: 'None', description: 'Move 8-bit immediate data into register H', example: 'MVI H, 20H' },
  { hex: '2E', mnemonic: 'MVI L, data', bytes: 2, tStates: '7', category: 'Data Transfer', flagsAffected: 'None', description: 'Move 8-bit immediate data into register L', example: 'MVI L, 50H' },
  { hex: '36', mnemonic: 'MVI M, data', bytes: 2, tStates: '10', category: 'Data Transfer', flagsAffected: 'None', description: 'Move 8-bit immediate data into memory location [HL]', example: 'MVI M, FFH' },

  { hex: '21', mnemonic: 'LXI H, addr16', bytes: 3, tStates: '10', category: 'Data Transfer', flagsAffected: 'None', description: 'Load 16-bit address/data immediately into H-L register pair', example: 'LXI H, 2050H' },
  { hex: '01', mnemonic: 'LXI B, addr16', bytes: 3, tStates: '10', category: 'Data Transfer', flagsAffected: 'None', description: 'Load 16-bit address/data immediately into B-C register pair', example: 'LXI B, 1000H' },
  { hex: '11', mnemonic: 'LXI D, addr16', bytes: 3, tStates: '10', category: 'Data Transfer', flagsAffected: 'None', description: 'Load 16-bit address/data immediately into D-E register pair', example: 'LXI D, 3000H' },
  { hex: '31', mnemonic: 'LXI SP, addr16', bytes: 3, tStates: '10', category: 'Data Transfer', flagsAffected: 'None', description: 'Load 16-bit address directly into Stack Pointer SP', example: 'LXI SP, 30FFH' },

  { hex: '3A', mnemonic: 'LDA addr16', bytes: 3, tStates: '13', category: 'Data Transfer', flagsAffected: 'None', description: 'Load Accumulator directly from 16-bit memory address', example: 'LDA 2050H' },
  { hex: '32', mnemonic: 'STA addr16', bytes: 3, tStates: '13', category: 'Data Transfer', flagsAffected: 'None', description: 'Store Accumulator directly to 16-bit memory address', example: 'STA 2051H' },
  { hex: '2A', mnemonic: 'LHLD addr16', bytes: 3, tStates: '16', category: 'Data Transfer', flagsAffected: 'None', description: 'Load H-L registers directly from specified 16-bit memory address', example: 'LHLD 2050H' },
  { hex: '22', mnemonic: 'SHLD addr16', bytes: 3, tStates: '16', category: 'Data Transfer', flagsAffected: 'None', description: 'Store H-L registers directly to specified 16-bit memory address', example: 'SHLD 2052H' },
  { hex: '0A', mnemonic: 'LDAX B', bytes: 1, tStates: '7', category: 'Data Transfer', flagsAffected: 'None', description: 'Load Accumulator indirectly from address in B-C pair', example: 'LDAX B' },
  { hex: '1A', mnemonic: 'LDAX D', bytes: 1, tStates: '7', category: 'Data Transfer', flagsAffected: 'None', description: 'Load Accumulator indirectly from address in D-E pair', example: 'LDAX D' },
  { hex: '02', mnemonic: 'STAX B', bytes: 1, tStates: '7', category: 'Data Transfer', flagsAffected: 'None', description: 'Store Accumulator indirectly to memory address in B-C pair', example: 'STAX B' },
  { hex: '12', mnemonic: 'STAX D', bytes: 1, tStates: '7', category: 'Data Transfer', flagsAffected: 'None', description: 'Store Accumulator indirectly to memory address in D-E pair', example: 'STAX D' },
  { hex: 'EB', mnemonic: 'XCHG', bytes: 1, tStates: '4', category: 'Data Transfer', flagsAffected: 'None', description: 'Exchange contents of H with D and L with E', example: 'XCHG' },

  // Arithmetic
  { hex: '80', mnemonic: 'ADD B', bytes: 1, tStates: '4', category: 'Arithmetic', flagsAffected: 'All (S, Z, AC, P, CY)', description: 'Add register B to Accumulator A', example: 'ADD B' },
  { hex: '81', mnemonic: 'ADD C', bytes: 1, tStates: '4', category: 'Arithmetic', flagsAffected: 'All', description: 'Add register C to Accumulator A', example: 'ADD C' },
  { hex: '82', mnemonic: 'ADD D', bytes: 1, tStates: '4', category: 'Arithmetic', flagsAffected: 'All', description: 'Add register D to Accumulator A', example: 'ADD D' },
  { hex: '83', mnemonic: 'ADD E', bytes: 1, tStates: '4', category: 'Arithmetic', flagsAffected: 'All', description: 'Add register E to Accumulator A', example: 'ADD E' },
  { hex: '84', mnemonic: 'ADD H', bytes: 1, tStates: '4', category: 'Arithmetic', flagsAffected: 'All', description: 'Add register H to Accumulator A', example: 'ADD H' },
  { hex: '85', mnemonic: 'ADD L', bytes: 1, tStates: '4', category: 'Arithmetic', flagsAffected: 'All', description: 'Add register L to Accumulator A', example: 'ADD L' },
  { hex: '86', mnemonic: 'ADD M', bytes: 1, tStates: '7', category: 'Arithmetic', flagsAffected: 'All', description: 'Add memory content at [HL] to Accumulator A', example: 'ADD M' },
  { hex: '87', mnemonic: 'ADD A', bytes: 1, tStates: '4', category: 'Arithmetic', flagsAffected: 'All', description: 'Add Accumulator A to itself (A = A + A)', example: 'ADD A' },

  { hex: '88', mnemonic: 'ADC B', bytes: 1, tStates: '4', category: 'Arithmetic', flagsAffected: 'All', description: 'Add register B and Carry flag to Accumulator A', example: 'ADC B' },
  { hex: '89', mnemonic: 'ADC C', bytes: 1, tStates: '4', category: 'Arithmetic', flagsAffected: 'All', description: 'Add register C and Carry flag to Accumulator A', example: 'ADC C' },
  { hex: '8E', mnemonic: 'ADC M', bytes: 1, tStates: '7', category: 'Arithmetic', flagsAffected: 'All', description: 'Add memory byte at [HL] + Carry to Accumulator', example: 'ADC M' },

  { hex: 'C6', mnemonic: 'ADI data', bytes: 2, tStates: '7', category: 'Arithmetic', flagsAffected: 'All', description: 'Add immediate 8-bit data to Accumulator A', example: 'ADI 05H' },
  { hex: 'CE', mnemonic: 'ACI data', bytes: 2, tStates: '7', category: 'Arithmetic', flagsAffected: 'All', description: 'Add immediate 8-bit data + Carry flag to Accumulator A', example: 'ACI 01H' },

  { hex: '90', mnemonic: 'SUB B', bytes: 1, tStates: '4', category: 'Arithmetic', flagsAffected: 'All', description: 'Subtract register B from Accumulator A', example: 'SUB B' },
  { hex: '91', mnemonic: 'SUB C', bytes: 1, tStates: '4', category: 'Arithmetic', flagsAffected: 'All', description: 'Subtract register C from Accumulator A', example: 'SUB C' },
  { hex: '96', mnemonic: 'SUB M', bytes: 1, tStates: '7', category: 'Arithmetic', flagsAffected: 'All', description: 'Subtract memory content [HL] from Accumulator A', example: 'SUB M' },
  { hex: 'D6', mnemonic: 'SUI data', bytes: 2, tStates: '7', category: 'Arithmetic', flagsAffected: 'All', description: 'Subtract immediate 8-bit data from Accumulator A', example: 'SUI 10H' },
  { hex: 'DE', mnemonic: 'SBI data', bytes: 2, tStates: '7', category: 'Arithmetic', flagsAffected: 'All', description: 'Subtract immediate data and Borrow/Carry from Accumulator', example: 'SBI 02H' },

  { hex: '04', mnemonic: 'INR B', bytes: 1, tStates: '5', category: 'Arithmetic', flagsAffected: 'S, Z, AC, P (CY unchanged)', description: 'Increment register B by 1', example: 'INR B' },
  { hex: '0C', mnemonic: 'INR C', bytes: 1, tStates: '5', category: 'Arithmetic', flagsAffected: 'S, Z, AC, P', description: 'Increment register C by 1', example: 'INR C' },
  { hex: '14', mnemonic: 'INR D', bytes: 1, tStates: '5', category: 'Arithmetic', flagsAffected: 'S, Z, AC, P', description: 'Increment register D by 1', example: 'INR D' },
  { hex: '1C', mnemonic: 'INR E', bytes: 1, tStates: '5', category: 'Arithmetic', flagsAffected: 'S, Z, AC, P', description: 'Increment register E by 1', example: 'INR E' },
  { hex: '24', mnemonic: 'INR H', bytes: 1, tStates: '5', category: 'Arithmetic', flagsAffected: 'S, Z, AC, P', description: 'Increment register H by 1', example: 'INR H' },
  { hex: '2C', mnemonic: 'INR L', bytes: 1, tStates: '5', category: 'Arithmetic', flagsAffected: 'S, Z, AC, P', description: 'Increment register L by 1', example: 'INR L' },
  { hex: '34', mnemonic: 'INR M', bytes: 1, tStates: '10', category: 'Arithmetic', flagsAffected: 'S, Z, AC, P', description: 'Increment memory byte at [HL] by 1', example: 'INR M' },
  { hex: '3C', mnemonic: 'INR A', bytes: 1, tStates: '5', category: 'Arithmetic', flagsAffected: 'S, Z, AC, P', description: 'Increment Accumulator A by 1', example: 'INR A' },

  { hex: '05', mnemonic: 'DCR B', bytes: 1, tStates: '5', category: 'Arithmetic', flagsAffected: 'S, Z, AC, P', description: 'Decrement register B by 1', example: 'DCR B' },
  { hex: '0D', mnemonic: 'DCR C', bytes: 1, tStates: '5', category: 'Arithmetic', flagsAffected: 'S, Z, AC, P', description: 'Decrement register C by 1', example: 'DCR C' },
  { hex: '15', mnemonic: 'DCR D', bytes: 1, tStates: '5', category: 'Arithmetic', flagsAffected: 'S, Z, AC, P', description: 'Decrement register D by 1', example: 'DCR D' },
  { hex: '1D', mnemonic: 'DCR E', bytes: 1, tStates: '5', category: 'Arithmetic', flagsAffected: 'S, Z, AC, P', description: 'Decrement register E by 1', example: 'DCR E' },
  { hex: '25', mnemonic: 'DCR H', bytes: 1, tStates: '5', category: 'Arithmetic', flagsAffected: 'S, Z, AC, P', description: 'Decrement register H by 1', example: 'DCR H' },
  { hex: '2D', mnemonic: 'DCR L', bytes: 1, tStates: '5', category: 'Arithmetic', flagsAffected: 'S, Z, AC, P', description: 'Decrement register L by 1', example: 'DCR L' },
  { hex: '35', mnemonic: 'DCR M', bytes: 1, tStates: '10', category: 'Arithmetic', flagsAffected: 'S, Z, AC, P', description: 'Decrement memory byte at [HL] by 1', example: 'DCR M' },
  { hex: '3D', mnemonic: 'DCR A', bytes: 1, tStates: '5', category: 'Arithmetic', flagsAffected: 'S, Z, AC, P', description: 'Decrement Accumulator A by 1', example: 'DCR A' },

  { hex: '03', mnemonic: 'INX B', bytes: 1, tStates: '6', category: 'Arithmetic', flagsAffected: 'None', description: 'Increment 16-bit register pair B-C by 1', example: 'INX B' },
  { hex: '13', mnemonic: 'INX D', bytes: 1, tStates: '6', category: 'Arithmetic', flagsAffected: 'None', description: 'Increment 16-bit register pair D-E by 1', example: 'INX D' },
  { hex: '23', mnemonic: 'INX H', bytes: 1, tStates: '6', category: 'Arithmetic', flagsAffected: 'None', description: 'Increment 16-bit register pair H-L by 1', example: 'INX H' },
  { hex: '0B', mnemonic: 'DCX B', bytes: 1, tStates: '6', category: 'Arithmetic', flagsAffected: 'None', description: 'Decrement 16-bit register pair B-C by 1', example: 'DCX B' },
  { hex: '1B', mnemonic: 'DCX D', bytes: 1, tStates: '6', category: 'Arithmetic', flagsAffected: 'None', description: 'Decrement 16-bit register pair D-E by 1', example: 'DCX D' },
  { hex: '2B', mnemonic: 'DCX H', bytes: 1, tStates: '6', category: 'Arithmetic', flagsAffected: 'None', description: 'Decrement 16-bit register pair H-L by 1', example: 'DCX H' },
  { hex: '27', mnemonic: 'DAA', bytes: 1, tStates: '4', category: 'Arithmetic', flagsAffected: 'All', description: 'Decimal Adjust Accumulator for BCD addition', example: 'DAA' },
  { hex: '09', mnemonic: 'DAD B', bytes: 1, tStates: '10', category: 'Arithmetic', flagsAffected: 'CY', description: 'Add register pair BC to HL pair', example: 'DAD B' },
  { hex: '19', mnemonic: 'DAD D', bytes: 1, tStates: '10', category: 'Arithmetic', flagsAffected: 'CY', description: 'Add register pair DE to HL pair', example: 'DAD D' },
  { hex: '29', mnemonic: 'DAD H', bytes: 1, tStates: '10', category: 'Arithmetic', flagsAffected: 'CY', description: 'Add register pair HL to HL pair (HL = HL * 2)', example: 'DAD H' },

  // Logical
  { hex: 'A0', mnemonic: 'ANA B', bytes: 1, tStates: '4', category: 'Logical', flagsAffected: 'S, Z, P, CY=0, AC=1', description: 'Logical AND register B with Accumulator A', example: 'ANA B' },
  { hex: 'A1', mnemonic: 'ANA C', bytes: 1, tStates: '4', category: 'Logical', flagsAffected: 'S, Z, P, CY=0, AC=1', description: 'Logical AND register C with Accumulator A', example: 'ANA C' },
  { hex: 'A6', mnemonic: 'ANA M', bytes: 1, tStates: '7', category: 'Logical', flagsAffected: 'S, Z, P, CY=0, AC=1', description: 'Logical AND memory [HL] with Accumulator', example: 'ANA M' },
  { hex: 'E6', mnemonic: 'ANI data', bytes: 2, tStates: '7', category: 'Logical', flagsAffected: 'S, Z, P, CY=0, AC=1', description: 'Logical AND immediate 8-bit data with Accumulator A', example: 'ANI 0FH' },

  { hex: 'B0', mnemonic: 'ORA B', bytes: 1, tStates: '4', category: 'Logical', flagsAffected: 'S, Z, P, CY=0, AC=0', description: 'Logical OR register B with Accumulator A', example: 'ORA B' },
  { hex: 'B1', mnemonic: 'ORA C', bytes: 1, tStates: '4', category: 'Logical', flagsAffected: 'S, Z, P, CY=0, AC=0', description: 'Logical OR register C with Accumulator A', example: 'ORA C' },
  { hex: 'F6', mnemonic: 'ORI data', bytes: 2, tStates: '7', category: 'Logical', flagsAffected: 'S, Z, P, CY=0, AC=0', description: 'Logical OR immediate 8-bit data with Accumulator', example: 'ORI 80H' },

  { hex: 'A8', mnemonic: 'XRA B', bytes: 1, tStates: '4', category: 'Logical', flagsAffected: 'S, Z, P, CY=0, AC=0', description: 'Logical XOR register B with Accumulator A', example: 'XRA B' },
  { hex: 'AF', mnemonic: 'XRA A', bytes: 1, tStates: '4', category: 'Logical', flagsAffected: 'S=0, Z=1, P=1, CY=0, AC=0', description: 'Clear Accumulator A to 00H', example: 'XRA A' },
  { hex: 'EE', mnemonic: 'XRI data', bytes: 2, tStates: '7', category: 'Logical', flagsAffected: 'S, Z, P, CY=0, AC=0', description: 'Logical XOR immediate data with Accumulator A', example: 'XRI FFH' },

  { hex: 'B8', mnemonic: 'CMP B', bytes: 1, tStates: '4', category: 'Logical', flagsAffected: 'S, Z, AC, P, CY', description: 'Compare register B with Accumulator (Subtract B without modifying A)', example: 'CMP B' },
  { hex: 'B9', mnemonic: 'CMP C', bytes: 1, tStates: '4', category: 'Logical', flagsAffected: 'All', description: 'Compare C with Accumulator A', example: 'CMP C' },
  { hex: 'BE', mnemonic: 'CMP M', bytes: 1, tStates: '7', category: 'Logical', flagsAffected: 'All', description: 'Compare memory byte at [HL] with Accumulator A', example: 'CMP M' },
  { hex: 'FE', mnemonic: 'CPI data', bytes: 2, tStates: '7', category: 'Logical', flagsAffected: 'All', description: 'Compare immediate 8-bit data with Accumulator A', example: 'CPI 00H' },

  { hex: '07', mnemonic: 'RLC', bytes: 1, tStates: '4', category: 'Logical', flagsAffected: 'CY', description: 'Rotate Accumulator left by 1 bit (D7 to D0 and CY)', example: 'RLC' },
  { hex: '0F', mnemonic: 'RRC', bytes: 1, tStates: '4', category: 'Logical', flagsAffected: 'CY', description: 'Rotate Accumulator right by 1 bit (D0 to D7 and CY)', example: 'RRC' },
  { hex: '17', mnemonic: 'RAL', bytes: 1, tStates: '4', category: 'Logical', flagsAffected: 'CY', description: 'Rotate Accumulator left through Carry flag', example: 'RAL' },
  { hex: '1F', mnemonic: 'RAR', bytes: 1, tStates: '4', category: 'Logical', flagsAffected: 'CY', description: 'Rotate Accumulator right through Carry flag', example: 'RAR' },
  { hex: '2F', mnemonic: 'CMA', bytes: 1, tStates: '4', category: 'Logical', flagsAffected: 'None', description: 'Complement Accumulator (1s complement / inverted bits)', example: 'CMA' },
  { hex: '37', mnemonic: 'STC', bytes: 1, tStates: '4', category: 'Logical', flagsAffected: 'CY=1', description: 'Set Carry flag to 1', example: 'STC' },
  { hex: '3F', mnemonic: 'CMC', bytes: 1, tStates: '4', category: 'Logical', flagsAffected: 'CY', description: 'Complement Carry flag', example: 'CMC' },

  // Branching & Jumps
  { hex: 'C3', mnemonic: 'JMP addr16', bytes: 3, tStates: '10', category: 'Branching', flagsAffected: 'None', description: 'Unconditional jump to 16-bit address', example: 'JMP 2000H' },
  { hex: 'DA', mnemonic: 'JC addr16', bytes: 3, tStates: '10/7', category: 'Branching', flagsAffected: 'None', description: 'Jump if Carry flag CY = 1', example: 'JC 2015H' },
  { hex: 'D2', mnemonic: 'JNC addr16', bytes: 3, tStates: '10/7', category: 'Branching', flagsAffected: 'None', description: 'Jump if Carry flag CY = 0', example: 'JNC 2020H' },
  { hex: 'CA', mnemonic: 'JZ addr16', bytes: 3, tStates: '10/7', category: 'Branching', flagsAffected: 'None', description: 'Jump if Zero flag Z = 1 (result is zero)', example: 'JZ 2030H' },
  { hex: 'C2', mnemonic: 'JNZ addr16', bytes: 3, tStates: '10/7', category: 'Branching', flagsAffected: 'None', description: 'Jump if Zero flag Z = 0 (result is non-zero)', example: 'JNZ 2008H' },
  { hex: 'F2', mnemonic: 'JP addr16', bytes: 3, tStates: '10/7', category: 'Branching', flagsAffected: 'None', description: 'Jump if Positive / Sign flag S = 0', example: 'JP 2040H' },
  { hex: 'FA', mnemonic: 'JM addr16', bytes: 3, tStates: '10/7', category: 'Branching', flagsAffected: 'None', description: 'Jump if Minus / Sign flag S = 1', example: 'JM 2045H' },
  { hex: 'EA', mnemonic: 'JPE addr16', bytes: 3, tStates: '10/7', category: 'Branching', flagsAffected: 'None', description: 'Jump if Parity Even P = 1', example: 'JPE 2050H' },
  { hex: 'E2', mnemonic: 'JPO addr16', bytes: 3, tStates: '10/7', category: 'Branching', flagsAffected: 'None', description: 'Jump if Parity Odd P = 0', example: 'JPO 2055H' },

  { hex: 'CD', mnemonic: 'CALL addr16', bytes: 3, tStates: '18', category: 'Branching', flagsAffected: 'None', description: 'Call subroutine at 16-bit address (pushes PC to stack)', example: 'CALL 3000H' },
  { hex: 'C9', mnemonic: 'RET', bytes: 1, tStates: '10', category: 'Branching', flagsAffected: 'None', description: 'Return from subroutine (pops return address into PC)', example: 'RET' },
  { hex: 'C5', mnemonic: 'PUSH B', bytes: 1, tStates: '12', category: 'Branching', flagsAffected: 'None', description: 'Push register pair B-C onto stack', example: 'PUSH B' },
  { hex: 'D5', mnemonic: 'PUSH D', bytes: 1, tStates: '12', category: 'Branching', flagsAffected: 'None', description: 'Push register pair D-E onto stack', example: 'PUSH D' },
  { hex: 'E5', mnemonic: 'PUSH H', bytes: 1, tStates: '12', category: 'Branching', flagsAffected: 'None', description: 'Push register pair H-L onto stack', example: 'PUSH H' },
  { hex: 'F5', mnemonic: 'PUSH PSW', bytes: 1, tStates: '12', category: 'Branching', flagsAffected: 'None', description: 'Push Accumulator A and Flags register (PSW) onto stack', example: 'PUSH PSW' },
  { hex: 'C1', mnemonic: 'POP B', bytes: 1, tStates: '10', category: 'Branching', flagsAffected: 'None', description: 'Pop top stack values into register pair B-C', example: 'POP B' },
  { hex: 'D1', mnemonic: 'POP D', bytes: 1, tStates: '10', category: 'Branching', flagsAffected: 'None', description: 'Pop top stack values into register pair D-E', example: 'POP D' },
  { hex: 'E1', mnemonic: 'POP H', bytes: 1, tStates: '10', category: 'Branching', flagsAffected: 'None', description: 'Pop top stack values into register pair H-L', example: 'POP H' },
  { hex: 'F1', mnemonic: 'POP PSW', bytes: 1, tStates: '10', category: 'Branching', flagsAffected: 'All', description: 'Pop top stack values into Accumulator A and Flags', example: 'POP PSW' },

  // Control & Machine
  { hex: '76', mnemonic: 'HLT', bytes: 1, tStates: '5', category: 'Control', flagsAffected: 'None', description: 'Halt microprocessor execution until next interrupt or reset', example: 'HLT' },
  { hex: '00', mnemonic: 'NOP', bytes: 1, tStates: '4', category: 'Control', flagsAffected: 'None', description: 'No Operation (delay of 4 T-states)', example: 'NOP' },
  { hex: 'FB', mnemonic: 'EI', bytes: 1, tStates: '4', category: 'Control', flagsAffected: 'None', description: 'Enable Interrupts', example: 'EI' },
  { hex: 'F3', mnemonic: 'DI', bytes: 1, tStates: '4', category: 'Control', flagsAffected: 'None', description: 'Disable Interrupts', example: 'DI' },
  { hex: 'DB', mnemonic: 'IN port', bytes: 2, tStates: '10', category: 'Control', flagsAffected: 'None', description: 'Read data byte from 8-bit I/O port into Accumulator A', example: 'IN 01H' },
  { hex: 'D3', mnemonic: 'OUT port', bytes: 2, tStates: '10', category: 'Control', flagsAffected: 'None', description: 'Output Accumulator A to specified 8-bit I/O port', example: 'OUT 02H' },
];
